name: Update Forks with PRs
on:
  workflow_dispatch: 

jobs:
  update-forks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the base repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install gh -y

      - name: Get the list of forks and create a PR
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          OWNER: "aandrxx"
          REPO: "initial_repo"
        run: |
          FORKS=$(gh api "/repos/$OWNER/$REPO/forks" --jq '.[].full_name')

          for FORK in $FORKS; do
            echo "Create a PR to: $FORK"

            gh pr create \
              --repo "$FORK" \
              --head "$OWNER:main" \
              --base "main" \
              --title "Update from the original repo" \
              --body "This is an update from the origin repo."
          done
